export const GET_ALL_COURSE_REQUEST = "GET_ALL_COURSE_REQUEST"
export const GET_ALL_COURSE_FAILURE = "GET_ALL_COURSE_FAILURE"
export const GET_ALL_COURSE_SUCCESS = "GET_ALL_COURSE_SUCCESS"

export const GET_ALL_EXPLORE_REQUEST = "GET_ALL_EXPLORE_REQUEST"
export const GET_ALL_EXPLORE_FAILURE = "GET_ALL_EXPLORE_FAILURE"
export const GET_ALL_EXPLORE_SUCCESS = "GET_ALL_EXPLORE_SUCCESS"